### ISSUE TITLE
Please update to angular 2 final

### ISSUE THREAD

**Issue by mralexivy** [dominique-mueller/angular2-notifier#2]
Best angular notifier, please update to angular 2 final!

**Comment by itsdevdom** [comment]
Working on that right now :)

**Comment by itsdevdom** [comment]
OK, I finally found the time to finish up the new version, ready to be used with Angular 2 Final.

However, I renamed the library from **angular2-notifier** to **angular-notifier**. Primary reason is the planed release cycle of Angular, in particular the major releases every six months. The new name is a preparation for that, allowing developers to see that this library will not only work with Angular 2, but also with Angular 3, Angular 4, and so on.

Therefore, you can find the new version right here: https://github.com/dominique-mueller/angular-notifier.

It's a complete rewrite. However, lots of the public API, configuration, and even underlying code is very similar. Migration should be as simple as reading and comparing both README files. In addition, it may be necessary to fix the module loading / bundling configurations.

Have fun coding! If you have any further questions, just leave another comment down below :)

**Comment by mralexivy** [comment]
Terrific news , thanks :)
